<a href="https://colab.research.google.com/github/Mir-Safwan-Marzouq/Machine-Learning/blob/main/Linear%20Regression%20Multiple%20Variable/Housing%20Price%20Prediction/Linear%20Regression%20with%20Multiple%20Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("/content/house.csv")
df

area  bedrooms  age  price
0  2600       3.0   20  27000
1  3000       4.0   15  35000
2  3200       NaN   18  36000
3  3600       3.0   30  35000
4  4000       5.0    8  50000

In [4]:
import math
bedroom_number = math.floor(df.bedrooms.median())
bedroom_number

3

**Data Preprocessing**

In [8]:
df.bedrooms = df.bedrooms.fillna(bedroom_number)
df

area  bedrooms  age  price
0  2600       3.0   20  27000
1  3000       4.0   15  35000
2  3200       3.0   18  36000
3  3600       3.0   30  35000
4  4000       5.0    8  50000

In [11]:
#create a linear regression class object
reg = linear_model.LinearRegression()
#fit model is used to train your model
reg.fit(df[['area', 'bedrooms', 'age']], df.price)   

LinearRegression()

In [13]:
reg.coef_

array([  12.4, -160. , -480. ])

In [15]:
reg.intercept_

5239.999999999989

In [19]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22760.])

In [21]:
reg.predict([[3000,3,15]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34760.])

In [24]:
12.4*3000 + (-160) * 3 + (-480) * 15 + 5239.999999999989

34759.999999999985